title: The GitHub Learning Blog of Andrew Layman
author: Andrew Layman
email: andrew@strongbrains.com
description: > # this means to ignore newlines until "baseurl:"
  A record of the various things I did while taking the GitHub Learning lab in December 2019

# social links
twitter_username: andrewlayman
github_username:  andrewlayman

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
