title: My awesome title
author: Andrew Layman
email: andrew@strongbrains.com
description: > # this means to ignore newlines until "baseurl:"
  The description of my pages blog.

# social links
twitter_username: your-twitter-handle
github_username:  andrewlayman

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
